{"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService"]]},"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/AGSAuthenticationManagerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/authenticationManager(_:didReceive:)"]}],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"AGSAuthenticationManagerDelegate Implementations","modules":[{"name":"Mappy"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mappy\/tracksservice\/agsauthenticationmanagerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mappy\/tracksservice\/agsauthenticationmanagerdelegate-implementations"]}],"references":{"doc://io.bemappy.Mappy/documentation/Mappy/TracksService/authenticationManager(_:didReceive:)":{"title":"authenticationManager(_:didReceive:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"authenticationManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AGSAuthenticationManager","kind":"typeIdentifier","text":"AGSAuthenticationManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"text":": ","kind":"text"},{"text":"AGSAuthenticationChallenge","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AGSAuthenticationChallenge"},{"kind":"text","text":")"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/authenticationManager(_:didReceive:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"authenticationManager:didReceiveAuthenticationChallenge:","kind":"identifier"}],"type":"topic","url":"\/documentation\/mappy\/tracksservice\/authenticationmanager(_:didreceive:)"},"doc://io.bemappy.Mappy/documentation/Mappy/TracksService":{"title":"TracksService","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TracksService","kind":"identifier"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService","abstract":[],"role":"symbol","navigatorTitle":[{"text":"TracksService","kind":"identifier"}],"type":"topic","url":"\/documentation\/mappy\/tracksservice"},"doc://io.bemappy.Mappy/documentation/Mappy":{"title":"Mappy","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","type":"topic","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"role":"collection","url":"\/documentation\/mappy","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/authenticationManager(_:didReceive:)"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService~1authenticationManager(_:didReceive:)\/title","value":"authenticationManager:didReceiveAuthenticationChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService~1authenticationManager(_:didReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"authenticationManager:didReceiveAuthenticationChallenge:","kind":"identifier"}]},{"op":"replace","value":"TracksService","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService\/title"},{"value":[{"text":"TracksService","kind":"identifier"}],"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}