{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"authenticationManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AGSAuthenticationManager","preciseIdentifier":"c:objc(cs)AGSAuthenticationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AGSAuthenticationChallenge","preciseIdentifier":"c:objc(cs)AGSAuthenticationChallenge"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mappy\/tracksservice\/authenticationmanager(_:didreceive:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mappy\/tracksservice\/authenticationmanager(_:didreceive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/authenticationManager(_:didReceive:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AGSAuthenticationManagerDelegate.authenticationManager(_:didReceive:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AGSAuthenticationManager","preciseIdentifier":"c:objc(cs)AGSAuthenticationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AGSAuthenticationChallenge","preciseIdentifier":"c:objc(cs)AGSAuthenticationChallenge"},{"kind":"text","text":")"}],"title":"authenticationManager(_:didReceive:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Mappy@objc(cs)TracksService(im)authenticationManager:didReceiveAuthenticationChallenge:","modules":[{"name":"Mappy"}],"navigatorTitle":[{"kind":"identifier","text":"authenticationManager:didReceiveAuthenticationChallenge:"}]},"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/AGSAuthenticationManagerDelegate-Implementations"]]},"references":{"doc://io.bemappy.Mappy/documentation/Mappy":{"role":"collection","title":"Mappy","abstract":[{"type":"text","text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","kind":"symbol","type":"topic","url":"\/documentation\/mappy"},"doc://io.bemappy.Mappy/documentation/Mappy/TracksService/AGSAuthenticationManagerDelegate-Implementations":{"role":"collectionGroup","title":"AGSAuthenticationManagerDelegate Implementations","abstract":[],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/AGSAuthenticationManagerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/mappy\/tracksservice\/agsauthenticationmanagerdelegate-implementations"},"doc://io.bemappy.Mappy/documentation/Mappy/TracksService/authenticationManager(_:didReceive:)":{"role":"symbol","title":"authenticationManager(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AGSAuthenticationManager","preciseIdentifier":"c:objc(cs)AGSAuthenticationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AGSAuthenticationChallenge","preciseIdentifier":"c:objc(cs)AGSAuthenticationChallenge"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/authenticationManager(_:didReceive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticationManager:didReceiveAuthenticationChallenge:"}],"url":"\/documentation\/mappy\/tracksservice\/authenticationmanager(_:didreceive:)"},"doc://io.bemappy.Mappy/documentation/Mappy/TracksService":{"role":"symbol","title":"TracksService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TracksService"}],"abstract":[],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TracksService"}],"url":"\/documentation\/mappy\/tracksservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"authenticationManager:didReceiveAuthenticationChallenge:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticationManager:didReceiveAuthenticationChallenge:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"authenticationManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AGSAuthenticationManager","preciseIdentifier":"c:objc(cs)AGSAuthenticationManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"authenticationManager"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveAuthenticationChallenge:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AGSAuthenticationChallenge","preciseIdentifier":"c:objc(cs)AGSAuthenticationChallenge"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService~1authenticationManager(_:didReceive:)\/title","value":"authenticationManager:didReceiveAuthenticationChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService~1authenticationManager(_:didReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticationManager:didReceiveAuthenticationChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService\/title","value":"TracksService"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService\/fragments","value":[{"kind":"identifier","text":"TracksService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}