{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"()","kind":"text"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/init()"},"kind":"symbol","variants":[{"paths":["\/documentation\/mappy\/tracksservice\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mappy\/tracksservice\/init()"]}],"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"init()","externalID":"c:@M@Mappy@objc(cs)TracksService(im)init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"modules":[{"name":"Mappy"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol"},"references":{"doc://io.bemappy.Mappy/documentation/Mappy/TracksService/init()":{"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/mappy\/tracksservice\/init()","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"abstract":[],"title":"init()","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/init()","kind":"symbol","role":"symbol"},"doc://io.bemappy.Mappy/documentation/Mappy/TracksService":{"title":"TracksService","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TracksService","kind":"identifier"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService","abstract":[],"role":"symbol","navigatorTitle":[{"text":"TracksService","kind":"identifier"}],"type":"topic","url":"\/documentation\/mappy\/tracksservice"},"doc://io.bemappy.Mappy/documentation/Mappy":{"title":"Mappy","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","type":"topic","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"role":"collection","url":"\/documentation\/mappy","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"init","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"value":"TracksService","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService\/fragments","value":[{"kind":"identifier","text":"TracksService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}