{"identifier":{"url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/AGSGeoViewTouchDelegate-Implementations","interfaceLanguage":"swift"},"sections":[],"kind":"article","topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/geoView(_:didTapAtScreenPoint:mapPoint:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView"]]},"metadata":{"roleHeading":"API Collection","title":"AGSGeoViewTouchDelegate Implementations","modules":[{"name":"Mappy"}],"role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mappy\/sceneview\/agsgeoviewtouchdelegate-implementations"]},{"paths":["\/documentation\/mappy\/sceneview\/agsgeoviewtouchdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/geoView(_:didTapAtScreenPoint:mapPoint:)":{"abstract":[],"type":"topic","title":"geoView(_:didTapAtScreenPoint:mapPoint:)","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/geoView(_:didTapAtScreenPoint:mapPoint:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"geoView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AGSGeoView","text":"AGSGeoView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didTapAtScreenPoint"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"mapPoint","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AGSPoint","text":"AGSPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"geoView:didTapAtScreenPoint:mapPoint:","kind":"identifier"}],"url":"\/documentation\/mappy\/sceneview\/geoview(_:didtapatscreenpoint:mappoint:)"},"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView":{"url":"\/documentation\/mappy\/sceneview","title":"SceneView","abstract":[{"type":"text","text":"SceneView is an UI class that helps in rendering the 3D map. Once the scene is loaded, add the scene to SceneView and then you can add the same to your UI hierarchy."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneView","kind":"identifier"}],"navigatorTitle":[{"text":"SceneView","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/geoView(_:didTapAtScreenPoint:mapPoint:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView~1geoView(_:didTapAtScreenPoint:mapPoint:)\/title","value":"geoView:didTapAtScreenPoint:mapPoint:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"geoView:didTapAtScreenPoint:mapPoint:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView~1geoView(_:didTapAtScreenPoint:mapPoint:)\/fragments"},{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/title","op":"replace","value":"SceneView"},{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/fragments","value":[{"kind":"identifier","text":"SceneView"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SceneView"}],"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}