{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"geoView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"geoView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AGSGeoView","preciseIdentifier":"c:objc(cs)AGSGeoView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapAtScreenPoint"},{"kind":"text","text":" "},{"kind":"internalParam","text":"screenPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mapPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AGSPoint","preciseIdentifier":"c:objc(cs)AGSPoint"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mappy\/sceneview\/geoview(_:didtapatscreenpoint:mappoint:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mappy\/sceneview\/geoview(_:didtapatscreenpoint:mappoint:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneView\/geoView(_:didTapAtScreenPoint:mapPoint:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AGSGeoViewTouchDelegate.geoView(_:didTapAtScreenPoint:mapPoint:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"geoView:didTapAtScreenPoint:mapPoint:"}],"role":"symbol","title":"geoView(_:didTapAtScreenPoint:mapPoint:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"geoView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AGSGeoView","preciseIdentifier":"c:objc(cs)AGSGeoView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapAtScreenPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mapPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AGSPoint","preciseIdentifier":"c:objc(cs)AGSPoint"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@Mappy@objc(cs)SceneView(im)geoView:didTapAtScreenPoint:mapPoint:","extendedModule":"Mappy","modules":[{"name":"Mappy"}]},"hierarchy":{"paths":[["doc:\/\/io.freshworks.Mappy\/documentation\/Mappy","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneView","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneView\/AGSGeoViewTouchDelegate-Implementations"]]},"references":{"doc://io.freshworks.Mappy/documentation/Mappy":{"role":"collection","title":"Mappy","abstract":[{"type":"text","text":"Hello World \/\/ Summary"}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy","kind":"symbol","type":"topic","url":"\/documentation\/mappy"},"doc://io.freshworks.Mappy/documentation/Mappy/SceneView":{"role":"symbol","title":"SceneView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneView"}],"abstract":[{"type":"text","text":"SceneView is an UI class that helps in rendering the 3D map. Once the scene is loaded, add the scene to SceneView and then you can add the same to your UI hierarchy."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SceneView"}],"url":"\/documentation\/mappy\/sceneview"},"doc://io.freshworks.Mappy/documentation/Mappy/SceneView/AGSGeoViewTouchDelegate-Implementations":{"role":"collectionGroup","title":"AGSGeoViewTouchDelegate Implementations","abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneView\/AGSGeoViewTouchDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/mappy\/sceneview\/agsgeoviewtouchdelegate-implementations"},"doc://io.freshworks.Mappy/documentation/Mappy/SceneView/geoView(_:didTapAtScreenPoint:mapPoint:)":{"role":"symbol","title":"geoView(_:didTapAtScreenPoint:mapPoint:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"geoView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AGSGeoView","preciseIdentifier":"c:objc(cs)AGSGeoView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapAtScreenPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mapPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AGSPoint","preciseIdentifier":"c:objc(cs)AGSPoint"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneView\/geoView(_:didTapAtScreenPoint:mapPoint:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"geoView:didTapAtScreenPoint:mapPoint:"}],"url":"\/documentation\/mappy\/sceneview\/geoview(_:didtapatscreenpoint:mappoint:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"geoView:didTapAtScreenPoint:mapPoint:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"geoView:didTapAtScreenPoint:mapPoint:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"geoView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AGSGeoView","preciseIdentifier":"c:objc(cs)AGSGeoView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"geoView"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapAtScreenPoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"},{"kind":"internalParam","text":"screenPoint"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapPoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AGSPoint","preciseIdentifier":"c:objc(cs)AGSPoint"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mapPoint"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.freshworks.Mappy~1documentation~1Mappy~1SceneView\/title","value":"SceneView"},{"op":"replace","path":"\/references\/doc:~1~1io.freshworks.Mappy~1documentation~1Mappy~1SceneView\/fragments","value":[{"kind":"identifier","text":"SceneView"}]},{"op":"replace","path":"\/references\/doc:~1~1io.freshworks.Mappy~1documentation~1Mappy~1SceneView~1geoView(_:didTapAtScreenPoint:mapPoint:)\/title","value":"geoView:didTapAtScreenPoint:mapPoint:"},{"op":"replace","path":"\/references\/doc:~1~1io.freshworks.Mappy~1documentation~1Mappy~1SceneView~1geoView(_:didTapAtScreenPoint:mapPoint:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"geoView:didTapAtScreenPoint:mapPoint:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}