{"abstract":[{"type":"text","text":"To toggle the track’s visibility"}],"metadata":{"title":"hideUserTrack()","extendedModule":"Mappy","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","modules":[{"name":"Mappy"}],"externalID":"s:5Mappy9SceneViewC13hideUserTrackyyF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideUserTrack","kind":"identifier"},{"text":"()","kind":"text"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"hideUserTrack","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/hideUserTrack()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mappy\/sceneview\/hideusertrack()"]}],"sections":[],"references":{"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/hideUserTrack()":{"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/hideUserTrack()","title":"hideUserTrack()","abstract":[{"type":"text","text":"To toggle the track’s visibility"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mappy\/sceneview\/hideusertrack()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hideUserTrack"},{"text":"()","kind":"text"}],"type":"topic"},"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView":{"url":"\/documentation\/mappy\/sceneview","title":"SceneView","abstract":[{"type":"text","text":"SceneView is an UI class that helps in rendering the 3D map. Once the scene is loaded, add the scene to SceneView and then you can add the same to your UI hierarchy."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneView","kind":"identifier"}],"navigatorTitle":[{"text":"SceneView","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"SceneView","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/title","op":"replace"},{"value":[{"text":"SceneView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/fragments"},{"value":[{"text":"SceneView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}