{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mappy\/sceneview\/ispointingnorth"]}],"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView"]]},"sections":[],"identifier":{"url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/isPointingNorth","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPointingNorth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","modules":[{"name":"Mappy"}],"title":"isPointingNorth","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPointingNorth","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","externalID":"s:5Mappy9SceneViewC15isPointingNorthSbvp","symbolKind":"property"},"kind":"symbol","abstract":[{"text":"Whether the scene is pointing north","type":"text"}],"references":{"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/isPointingNorth":{"type":"topic","abstract":[{"text":"Whether the scene is pointing north","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPointingNorth"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/mappy\/sceneview\/ispointingnorth","role":"symbol","kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/isPointingNorth","title":"isPointingNorth"},"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView":{"url":"\/documentation\/mappy\/sceneview","title":"SceneView","abstract":[{"type":"text","text":"SceneView is an UI class that helps in rendering the 3D map. Once the scene is loaded, add the scene to SceneView and then you can add the same to your UI hierarchy."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneView","kind":"identifier"}],"navigatorTitle":[{"text":"SceneView","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/title","value":"SceneView"},{"value":[{"kind":"identifier","text":"SceneView"}],"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/fragments"},{"value":[{"text":"SceneView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/navigatorTitle"}]}]}