{"sections":[],"abstract":[{"type":"text","text":"Renders the user track on the scene."}],"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderUserTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"startTime","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"endTime","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil) -> "},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/UserTrackRenderingStatus","preciseIdentifier":"s:5Mappy9SceneViewC24UserTrackRenderingStatusO","text":"UserTrackRenderingStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"startTime","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The time from which the tracks are rendered."}]}]},{"name":"endTime","content":[{"inlineContent":[{"type":"text","text":"The time to which the tracks are rendered."}],"type":"paragraph"}]}]},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A publisher that completes without a value or fails with error.","type":"text"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/renderUserTrack(startTime:endTime:userId:)"},"metadata":{"externalID":"s:5Mappy9SceneViewC15renderUserTrack9startTime03endH06userId7Combine12AnyPublisherVyAC0eF15RenderingStatusOs5Error_pGSd_SdSSSgtF","title":"renderUserTrack(startTime:endTime:userId:)","extendedModule":"Mappy","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"Mappy"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderUserTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"startTime"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"endTime","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"kind":"text","text":"<"},{"text":"UserTrackRenderingStatus","kind":"typeIdentifier","preciseIdentifier":"s:5Mappy9SceneViewC24UserTrackRenderingStatusO"},{"text":", ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mappy\/sceneview\/renderusertrack(starttime:endtime:userid:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://io.bemappy.Mappy/documentation/Mappy/SceneView":{"url":"\/documentation\/mappy\/sceneview","title":"SceneView","abstract":[{"type":"text","text":"SceneView is an UI class that helps in rendering the 3D map. Once the scene is loaded, add the scene to SceneView and then you can add the same to your UI hierarchy."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneView","kind":"identifier"}],"navigatorTitle":[{"text":"SceneView","kind":"identifier"}],"type":"topic"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/renderUserTrack(startTime:endTime:userId:)":{"url":"\/documentation\/mappy\/sceneview\/renderusertrack(starttime:endtime:userid:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"renderUserTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"startTime","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"endTime","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5Mappy9SceneViewC24UserTrackRenderingStatusO","text":"UserTrackRenderingStatus"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":">","kind":"text"}],"type":"topic","abstract":[{"text":"Renders the user track on the scene.","type":"text"}],"title":"renderUserTrack(startTime:endTime:userId:)","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/renderUserTrack(startTime:endTime:userId:)"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/UserTrackRenderingStatus":{"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserTrackRenderingStatus","kind":"identifier"}],"url":"\/documentation\/mappy\/sceneview\/usertrackrenderingstatus","kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/UserTrackRenderingStatus","type":"topic","title":"SceneView.UserTrackRenderingStatus","role":"symbol","navigatorTitle":[{"text":"UserTrackRenderingStatus","kind":"identifier"}]},"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/title","value":"SceneView","op":"replace"},{"value":[{"text":"SceneView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/fragments"},{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/navigatorTitle","value":[{"kind":"identifier","text":"SceneView"}],"op":"replace"}]}]}