{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"extendedModule":"Mappy","symbolKind":"method","externalID":"s:5Mappy9SceneViewC6select7featureyAA7FeatureVSg_tF","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"Mappy"}],"title":"select(feature:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"select","kind":"identifier"},{"kind":"text","text":"("},{"text":"feature","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5Mappy7FeatureV","text":"Feature","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"A function that highlights and zooms to the feature provided"},{"type":"text","text":" "},{"text":"If the provided feature is nil then it removes any existing selection on the scene","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"select","kind":"identifier"},{"kind":"text","text":"("},{"text":"feature","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/Feature","text":"Feature","preciseIdentifier":"s:5Mappy7FeatureV","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mappy\/sceneview\/select(feature:)"]}],"identifier":{"url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/select(feature:)","interfaceLanguage":"swift"},"references":{"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView":{"url":"\/documentation\/mappy\/sceneview","title":"SceneView","abstract":[{"type":"text","text":"SceneView is an UI class that helps in rendering the 3D map. Once the scene is loaded, add the scene to SceneView and then you can add the same to your UI hierarchy."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneView","kind":"identifier"}],"navigatorTitle":[{"text":"SceneView","kind":"identifier"}],"type":"topic"},"doc://io.bemappy.Mappy/documentation/Mappy/Feature":{"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/Feature","title":"Feature","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Feature","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A response for map search autocomplete suggestions.","type":"text"}],"navigatorTitle":[{"text":"Feature","kind":"identifier"}],"url":"\/documentation\/mappy\/feature","type":"topic","kind":"symbol"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/select(feature:)":{"type":"topic","url":"\/documentation\/mappy\/sceneview\/select(feature:)","kind":"symbol","abstract":[{"type":"text","text":"A function that highlights and zooms to the feature provided"},{"type":"text","text":" "},{"type":"text","text":"If the provided feature is nil then it removes any existing selection on the scene"}],"title":"select(feature:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"select","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"feature"},{"text":": ","kind":"text"},{"text":"Feature","preciseIdentifier":"s:5Mappy7FeatureV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/select(feature:)","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SceneView","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/title","op":"replace"},{"value":[{"text":"SceneView","kind":"identifier"}],"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SceneView"}],"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}