{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserTrackRenderingStatus","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView"]]},"topicSections":[{"identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/UserTrackRenderingStatus\/empty","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/UserTrackRenderingStatus\/normal"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/UserTrackRenderingStatus\/Equatable-Implementations"]}],"variants":[{"paths":["\/documentation\/mappy\/sceneview\/usertrackrenderingstatus"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/UserTrackRenderingStatus"},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/io.bemappy.Mappy\/SQ","doc:\/\/io.bemappy.Mappy\/SH"],"type":"conformsTo"}],"sections":[],"metadata":{"roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UserTrackRenderingStatus","kind":"identifier"}],"role":"symbol","title":"SceneView.UserTrackRenderingStatus","extendedModule":"Mappy","navigatorTitle":[{"text":"UserTrackRenderingStatus","kind":"identifier"}],"externalID":"s:5Mappy9SceneViewC24UserTrackRenderingStatusO","modules":[{"name":"Mappy"}],"symbolKind":"enum"},"references":{"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/UserTrackRenderingStatus":{"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserTrackRenderingStatus","kind":"identifier"}],"url":"\/documentation\/mappy\/sceneview\/usertrackrenderingstatus","kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/UserTrackRenderingStatus","type":"topic","title":"SceneView.UserTrackRenderingStatus","role":"symbol","navigatorTitle":[{"text":"UserTrackRenderingStatus","kind":"identifier"}]},"doc://io.bemappy.Mappy/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/SH"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/UserTrackRenderingStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/mappy\/sceneview\/usertrackrenderingstatus\/equatable-implementations","abstract":[],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/UserTrackRenderingStatus\/Equatable-Implementations","kind":"article","type":"topic"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/UserTrackRenderingStatus/empty":{"url":"\/documentation\/mappy\/sceneview\/usertrackrenderingstatus\/empty","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/UserTrackRenderingStatus\/empty","title":"SceneView.UserTrackRenderingStatus.empty","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"empty"}],"role":"symbol"},"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/UserTrackRenderingStatus/normal":{"type":"topic","abstract":[],"role":"symbol","title":"SceneView.UserTrackRenderingStatus.normal","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/UserTrackRenderingStatus\/normal","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normal","kind":"identifier"}],"url":"\/documentation\/mappy\/sceneview\/usertrackrenderingstatus\/normal"},"doc://io.bemappy.Mappy/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/io.bemappy.Mappy\/SQ"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView":{"url":"\/documentation\/mappy\/sceneview","title":"SceneView","abstract":[{"type":"text","text":"SceneView is an UI class that helps in rendering the 3D map. Once the scene is loaded, add the scene to SceneView and then you can add the same to your UI hierarchy."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SceneView","kind":"identifier"}],"navigatorTitle":[{"text":"SceneView","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SceneView","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/fragments","value":[{"text":"SceneView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/navigatorTitle","value":[{"kind":"identifier","text":"SceneView"}]}]}]}