{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"empty","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/UserTrackRenderingStatus\/empty"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"empty"}],"symbolKind":"case","title":"MapView.UserTrackRenderingStatus.empty","roleHeading":"Case","externalID":"s:5Mappy7MapViewC24UserTrackRenderingStatusO5emptyyA2EmF","role":"symbol","modules":[{"name":"Mappy"}]},"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/UserTrackRenderingStatus"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mappy\/mapview\/usertrackrenderingstatus\/empty"]}],"references":{"doc://io.bemappy.Mappy/documentation/Mappy/MapView/UserTrackRenderingStatus/empty":{"title":"MapView.UserTrackRenderingStatus.empty","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"empty","kind":"identifier"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/UserTrackRenderingStatus\/empty","role":"symbol","url":"\/documentation\/mappy\/mapview\/usertrackrenderingstatus\/empty"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/UserTrackRenderingStatus":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UserTrackRenderingStatus","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"UserTrackRenderingStatus","kind":"identifier"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/UserTrackRenderingStatus","title":"MapView.UserTrackRenderingStatus","abstract":[],"url":"\/documentation\/mappy\/mapview\/usertrackrenderingstatus"},"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView":{"abstract":[{"type":"text","text":"MapView is an UI class that helps in rendering the 2D map. Once the map is loaded, add the map to MapView and then you can add the same to your UI hierarchy."}],"title":"MapView","type":"topic","kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView","url":"\/documentation\/mappy\/mapview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapView","kind":"identifier"}],"navigatorTitle":[{"text":"MapView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/title","value":"MapView"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/fragments","value":[{"kind":"identifier","text":"MapView"}]},{"value":[{"kind":"identifier","text":"MapView"}],"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}