{"variants":[{"paths":["\/documentation\/mappy\/mapview\/usertrackrenderingstatus\/normal"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"Mappy"}],"externalID":"s:5Mappy7MapViewC24UserTrackRenderingStatusO6normalyA2EmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normal","kind":"identifier"}],"symbolKind":"case","role":"symbol","roleHeading":"Case","title":"MapView.UserTrackRenderingStatus.normal"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"normal"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/UserTrackRenderingStatus"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/UserTrackRenderingStatus\/normal"},"sections":[],"references":{"doc://io.bemappy.Mappy/documentation/Mappy/MapView":{"abstract":[{"type":"text","text":"MapView is an UI class that helps in rendering the 2D map. Once the map is loaded, add the map to MapView and then you can add the same to your UI hierarchy."}],"title":"MapView","type":"topic","kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView","url":"\/documentation\/mappy\/mapview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapView","kind":"identifier"}],"navigatorTitle":[{"text":"MapView","kind":"identifier"}]},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/UserTrackRenderingStatus/normal":{"kind":"symbol","type":"topic","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/UserTrackRenderingStatus\/normal","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"normal"}],"title":"MapView.UserTrackRenderingStatus.normal","role":"symbol","url":"\/documentation\/mappy\/mapview\/usertrackrenderingstatus\/normal","abstract":[]},"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/UserTrackRenderingStatus":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UserTrackRenderingStatus","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"UserTrackRenderingStatus","kind":"identifier"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/UserTrackRenderingStatus","title":"MapView.UserTrackRenderingStatus","abstract":[],"url":"\/documentation\/mappy\/mapview\/usertrackrenderingstatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/title","value":"MapView"},{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/fragments","value":[{"text":"MapView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/navigatorTitle","value":[{"kind":"identifier","text":"MapView"}]}]}]}