{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Hello World"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mappy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mappy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Hello World \/\/ Summary"}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"Mappy","title":"Mappy","symbolKind":"module","role":"collection","modules":[{"name":"Mappy"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/GroupLocationService","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/GroupsService","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Map","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapView","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MappyCore","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/RouteTracker","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Scene","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneView","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/VenuesService"]},{"title":"Protocols","identifiers":["doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/DirectionEvent","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/DirectionMessage","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Loadable","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapInfo","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneInfo","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Serializable"]},{"title":"Structures","identifiers":["doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Bookmark","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Building","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/BuildingAmenity","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/DirectionManeuver","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Feature","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Group","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/GroupUser","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapRegion","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapViewInteractionOptions","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MappyMeta","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/NavigationStep","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/NavigationUpcomingDirection","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Point","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/RouteModel","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/RouteResponse","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/RouteStepModel","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneViewInteractionOptions","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SkiLift","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SkiSlope","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/TurnByTurnNavigationResponse","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/UserLocation","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/UserPinLocation","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Venue","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/VenueData","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/VenueGeoReference","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/VenueTerrainPercentage"]},{"title":"Enumerations","identifiers":["doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/DirectionManeuverType","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/DirectionMessageType","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Environment","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/FeatureCategory","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/GroupLocationServiceError","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/GroupsProviderError","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/LoadStatus","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapError","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapType","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MappyCoreError","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneError","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/VenuesProviderError"]}],"references":{"doc://io.freshworks.Mappy/documentation/Mappy/Serializable":{"role":"symbol","title":"Serializable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Serializable"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Serializable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Serializable"}],"url":"\/documentation\/mappy\/serializable"},"doc://io.freshworks.Mappy/documentation/Mappy/FeatureCategory":{"role":"symbol","title":"FeatureCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureCategory"}],"abstract":[{"type":"text","text":"The different types of Features in a map or scene"}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/FeatureCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeatureCategory"}],"url":"\/documentation\/mappy\/featurecategory"},"doc://io.freshworks.Mappy/documentation/Mappy/SceneInfo":{"role":"symbol","title":"SceneInfo","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneInfo"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SceneInfo"}],"url":"\/documentation\/mappy\/sceneinfo"},"doc://io.freshworks.Mappy/documentation/Mappy/Point":{"role":"symbol","title":"Point","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Point"}],"abstract":[{"type":"text","text":"Data related to custom points on the map"}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Point","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Point"}],"url":"\/documentation\/mappy\/point"},"doc://io.freshworks.Mappy/documentation/Mappy/DirectionMessageType":{"role":"symbol","title":"DirectionMessageType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DirectionMessageType"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/DirectionMessageType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DirectionMessageType"}],"url":"\/documentation\/mappy\/directionmessagetype"},"doc://io.freshworks.Mappy/documentation/Mappy/GroupLocationService":{"role":"symbol","title":"GroupLocationService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupLocationService"}],"abstract":[{"type":"text","text":"The GroupLocationService helps in sharing the user’s location to all the user groups and can listen to other group members’ location updates."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/GroupLocationService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupLocationService"}],"url":"\/documentation\/mappy\/grouplocationservice"},"doc://io.freshworks.Mappy/documentation/Mappy/BuildingAmenity":{"role":"symbol","title":"BuildingAmenity","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BuildingAmenity"}],"abstract":[{"type":"text","text":"Data related to a building amenity"}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/BuildingAmenity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BuildingAmenity"}],"url":"\/documentation\/mappy\/buildingamenity"},"doc://io.freshworks.Mappy/documentation/Mappy/MapView":{"role":"symbol","title":"MapView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapView"}],"abstract":[{"type":"text","text":"MapView is an UI class that helps in rendering the 2D map. Once the map is loaded, add the map to MapView and then you can add the same to your UI hierarchy."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapView"}],"url":"\/documentation\/mappy\/mapview"},"doc://io.freshworks.Mappy/documentation/Mappy/DirectionManeuverType":{"role":"symbol","title":"DirectionManeuverType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DirectionManeuverType"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/DirectionManeuverType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DirectionManeuverType"}],"url":"\/documentation\/mappy\/directionmaneuvertype"},"doc://io.freshworks.Mappy/documentation/Mappy/GroupsProviderError":{"role":"symbol","title":"GroupsProviderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupsProviderError"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/GroupsProviderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupsProviderError"}],"url":"\/documentation\/mappy\/groupsprovidererror"},"doc://io.freshworks.Mappy/documentation/Mappy/VenuesProviderError":{"role":"symbol","title":"VenuesProviderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VenuesProviderError"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/VenuesProviderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VenuesProviderError"}],"url":"\/documentation\/mappy\/venuesprovidererror"},"doc://io.freshworks.Mappy/documentation/Mappy/Feature":{"role":"symbol","title":"Feature","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Feature"}],"abstract":[{"type":"text","text":"A response for map search autocomplete suggestions."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Feature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Feature"}],"url":"\/documentation\/mappy\/feature"},"doc://io.freshworks.Mappy/documentation/Mappy/MapViewInteractionOptions":{"role":"symbol","title":"MapViewInteractionOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapViewInteractionOptions"}],"abstract":[{"type":"text","text":"Options to configure Map View user interactions"},{"type":"text","text":" "},{"type":"text","text":"Instances of this struct provide options to configure the user interactions supported by MapView."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapViewInteractionOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapViewInteractionOptions"}],"url":"\/documentation\/mappy\/mapviewinteractionoptions"},"doc://io.freshworks.Mappy/documentation/Mappy/MappyCore":{"role":"symbol","title":"MappyCore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MappyCore"}],"abstract":[{"type":"text","text":"The gateway of the SDK. Configurational operations performed using this type."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MappyCore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MappyCore"}],"url":"\/documentation\/mappy\/mappycore"},"doc://io.freshworks.Mappy/documentation/Mappy/GroupUser":{"role":"symbol","title":"GroupUser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupUser"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/GroupUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupUser"}],"url":"\/documentation\/mappy\/groupuser"},"doc://io.freshworks.Mappy/documentation/Mappy/MappyVersionNumber":{"role":"symbol","title":"MappyVersionNumber","fragments":[{"kind":"identifier","text":"MappyVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for Mappy."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MappyVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/mappyversionnumber"},"doc://io.freshworks.Mappy/documentation/Mappy/SceneView":{"role":"symbol","title":"SceneView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneView"}],"abstract":[{"type":"text","text":"SceneView is an UI class that helps in rendering the 3D map. Once the scene is loaded, add the scene to SceneView and then you can add the same to your UI hierarchy."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SceneView"}],"url":"\/documentation\/mappy\/sceneview"},"doc://io.freshworks.Mappy/documentation/Mappy/MappyCoreError":{"role":"symbol","title":"MappyCoreError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MappyCoreError"}],"abstract":[{"type":"text","text":"Errors thrown from MappyCore"}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MappyCoreError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MappyCoreError"}],"url":"\/documentation\/mappy\/mappycoreerror"},"doc://io.freshworks.Mappy/documentation/Mappy/MapType":{"role":"symbol","title":"MapType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapType"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapType"}],"url":"\/documentation\/mappy\/maptype"},"doc://io.freshworks.Mappy/documentation/Mappy/DirectionEvent":{"role":"symbol","title":"DirectionEvent","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DirectionEvent"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/DirectionEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DirectionEvent"}],"url":"\/documentation\/mappy\/directionevent"},"doc://io.freshworks.Mappy/documentation/Mappy/DirectionManeuver":{"role":"symbol","title":"DirectionManeuver","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DirectionManeuver"}],"abstract":[{"type":"text","text":"A single maneuver in a series of driving direction"}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/DirectionManeuver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DirectionManeuver"}],"url":"\/documentation\/mappy\/directionmaneuver"},"doc://io.freshworks.Mappy/documentation/Mappy/GroupLocationServiceError":{"role":"symbol","title":"GroupLocationServiceError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupLocationServiceError"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/GroupLocationServiceError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupLocationServiceError"}],"url":"\/documentation\/mappy\/grouplocationserviceerror"},"doc://io.freshworks.Mappy/documentation/Mappy/Bookmark":{"role":"symbol","title":"Bookmark","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bookmark"}],"abstract":[{"type":"text","text":"Data related to a bookmark"}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Bookmark","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Bookmark"}],"url":"\/documentation\/mappy\/bookmark"},"doc://io.freshworks.Mappy/documentation/Mappy/UserLocation":{"role":"symbol","title":"UserLocation","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserLocation"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/UserLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserLocation"}],"url":"\/documentation\/mappy\/userlocation"},"doc://io.freshworks.Mappy/documentation/Mappy/GroupsService":{"role":"symbol","title":"GroupsService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupsService"}],"abstract":[{"type":"text","text":"The GroupsService helps in creating, reading, updating and deleting groups. It can also add or remove users to and from the groups. It is mandatory to initialize the SDK before creating the instance and invoking the functions of this service."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/GroupsService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupsService"}],"url":"\/documentation\/mappy\/groupsservice"},"doc://io.freshworks.Mappy/documentation/Mappy/TurnByTurnNavigationResponse":{"role":"symbol","title":"TurnByTurnNavigationResponse","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TurnByTurnNavigationResponse"}],"abstract":[{"type":"text","text":"Status of the route navigation"}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/TurnByTurnNavigationResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TurnByTurnNavigationResponse"}],"url":"\/documentation\/mappy\/turnbyturnnavigationresponse"},"doc://io.freshworks.Mappy/documentation/Mappy/Group":{"role":"symbol","title":"Group","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Group"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Group","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Group"}],"url":"\/documentation\/mappy\/group"},"doc://io.freshworks.Mappy/documentation/Mappy/RouteResponse":{"role":"symbol","title":"RouteResponse","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteResponse"}],"abstract":[{"type":"text","text":"A response for a request to find routes."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/RouteResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RouteResponse"}],"url":"\/documentation\/mappy\/routeresponse"},"doc://io.freshworks.Mappy/documentation/Mappy/RouteStepModel":{"role":"symbol","title":"RouteStepModel","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteStepModel"}],"abstract":[{"type":"text","text":"A struct having details about the quantified representation of a particular difficulty in the route."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/RouteStepModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RouteStepModel"}],"url":"\/documentation\/mappy\/routestepmodel"},"doc://io.freshworks.Mappy/documentation/Mappy/LoadStatus":{"role":"symbol","title":"LoadStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoadStatus"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/LoadStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoadStatus"}],"url":"\/documentation\/mappy\/loadstatus"},"doc://io.freshworks.Mappy/documentation/Mappy/NavigationUpcomingDirection":{"role":"symbol","title":"NavigationUpcomingDirection","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationUpcomingDirection"}],"abstract":[{"type":"text","text":"Contains the type of direction maneuver and distance."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/NavigationUpcomingDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationUpcomingDirection"}],"url":"\/documentation\/mappy\/navigationupcomingdirection"},"doc://io.freshworks.Mappy/documentation/Mappy/MappyMeta":{"role":"symbol","title":"MappyMeta","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MappyMeta"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MappyMeta","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MappyMeta"}],"url":"\/documentation\/mappy\/mappymeta"},"doc://io.freshworks.Mappy/documentation/Mappy/Environment":{"role":"symbol","title":"Environment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Environment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Environment"}],"url":"\/documentation\/mappy\/environment"},"doc://io.freshworks.Mappy/documentation/Mappy/RouteTracker":{"role":"symbol","title":"RouteTracker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteTracker"}],"abstract":[{"type":"text","text":"Uses a location to provide status and progress updates as a route is traversed (by a moving vehicle, for example)."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/RouteTracker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RouteTracker"}],"url":"\/documentation\/mappy\/routetracker"},"doc://io.freshworks.Mappy/documentation/Mappy/SceneError":{"role":"symbol","title":"SceneError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneError"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SceneError"}],"url":"\/documentation\/mappy\/sceneerror"},"doc://io.freshworks.Mappy/documentation/Mappy/RouteModel":{"role":"symbol","title":"RouteModel","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteModel"}],"abstract":[{"type":"text","text":"A struct containing high level attributes derived from a RouteResponse."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/RouteModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RouteModel"}],"url":"\/documentation\/mappy\/routemodel"},"doc://io.freshworks.Mappy/documentation/Mappy/UserPinLocation":{"role":"symbol","title":"UserPinLocation","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserPinLocation"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/UserPinLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserPinLocation"}],"url":"\/documentation\/mappy\/userpinlocation"},"doc://io.freshworks.Mappy/documentation/Mappy/MapError":{"role":"symbol","title":"MapError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapError"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapError"}],"url":"\/documentation\/mappy\/maperror"},"doc://io.freshworks.Mappy/documentation/Mappy/Scene":{"role":"symbol","title":"Scene","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scene"}],"abstract":[{"type":"text","text":"A scene is a class that represents the 3D map. You need to inject in all the required data associated with a venue to instantiate and load a Scene."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Scene","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Scene"}],"url":"\/documentation\/mappy\/scene"},"doc://io.freshworks.Mappy/documentation/Mappy/MapInfo":{"role":"symbol","title":"MapInfo","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapInfo"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapInfo"}],"url":"\/documentation\/mappy\/mapinfo"},"doc://io.freshworks.Mappy/documentation/Mappy":{"role":"collection","title":"Mappy","abstract":[{"type":"text","text":"Hello World \/\/ Summary"}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy","kind":"symbol","type":"topic","url":"\/documentation\/mappy"},"doc://io.freshworks.Mappy/documentation/Mappy/VenueTerrainPercentage":{"role":"symbol","title":"VenueTerrainPercentage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VenueTerrainPercentage"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/VenueTerrainPercentage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VenueTerrainPercentage"}],"url":"\/documentation\/mappy\/venueterrainpercentage"},"doc://io.freshworks.Mappy/documentation/Mappy/VenueGeoReference":{"role":"symbol","title":"VenueGeoReference","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VenueGeoReference"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/VenueGeoReference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VenueGeoReference"}],"url":"\/documentation\/mappy\/venuegeoreference"},"doc://io.freshworks.Mappy/documentation/Mappy/SkiSlope":{"role":"symbol","title":"SkiSlope","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SkiSlope"}],"abstract":[{"type":"text","text":"Data related to a ski slope"}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SkiSlope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SkiSlope"}],"url":"\/documentation\/mappy\/skislope"},"doc://io.freshworks.Mappy/documentation/Mappy/MapRegion":{"role":"symbol","title":"MapRegion","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapRegion"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapRegion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapRegion"}],"url":"\/documentation\/mappy\/mapregion"},"doc://io.freshworks.Mappy/documentation/Mappy/Building":{"role":"symbol","title":"Building","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Building"}],"abstract":[{"type":"text","text":"Data related to a building"}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Building","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Building"}],"url":"\/documentation\/mappy\/building"},"doc://io.freshworks.Mappy/documentation/Mappy/NavigationStep":{"role":"symbol","title":"NavigationStep","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationStep"}],"abstract":[{"type":"text","text":"A struct having details about a step in the navigation to reach the destination."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/NavigationStep","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NavigationStep"}],"url":"\/documentation\/mappy\/navigationstep"},"doc://io.freshworks.Mappy/documentation/Mappy/MappyVersionString":{"role":"symbol","title":"MappyVersionString","fragments":[{"kind":"identifier","text":"MappyVersionString"}],"abstract":[{"type":"text","text":"Project version string for Mappy."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MappyVersionString","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/mappyversionstring"},"doc://io.freshworks.Mappy/documentation/Mappy/VenuesService":{"role":"symbol","title":"VenuesService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VenuesService"}],"abstract":[{"type":"text","text":"A service to get the venues"}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/VenuesService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VenuesService"}],"url":"\/documentation\/mappy\/venuesservice"},"doc://io.freshworks.Mappy/documentation/Mappy/SceneViewInteractionOptions":{"role":"symbol","title":"SceneViewInteractionOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneViewInteractionOptions"}],"abstract":[{"type":"text","text":"Instances of this class provide options to configure the user interactions supported by @c SceneView."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneViewInteractionOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SceneViewInteractionOptions"}],"url":"\/documentation\/mappy\/sceneviewinteractionoptions"},"doc://io.freshworks.Mappy/documentation/Mappy/Loadable":{"role":"symbol","title":"Loadable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Loadable"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Loadable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Loadable"}],"url":"\/documentation\/mappy\/loadable"},"doc://io.freshworks.Mappy/documentation/Mappy/Map":{"role":"symbol","title":"Map","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Map"}],"abstract":[{"type":"text","text":"A Map is a class that represents the 2D map. You need to inject all the required data associated with a venue to instantiate and load a Map."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Map","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Map"}],"url":"\/documentation\/mappy\/map"},"doc://io.freshworks.Mappy/documentation/Mappy/SkiLift":{"role":"symbol","title":"SkiLift","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SkiLift"}],"abstract":[{"type":"text","text":"Data related to a ski lift."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SkiLift","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SkiLift"}],"url":"\/documentation\/mappy\/skilift"},"doc://io.freshworks.Mappy/documentation/Mappy/DirectionMessage":{"role":"symbol","title":"DirectionMessage","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DirectionMessage"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/DirectionMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DirectionMessage"}],"url":"\/documentation\/mappy\/directionmessage"},"doc://io.freshworks.Mappy/documentation/Mappy/VenueData":{"role":"symbol","title":"VenueData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VenueData"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/VenueData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VenueData"}],"url":"\/documentation\/mappy\/venuedata"},"doc://io.freshworks.Mappy/documentation/Mappy/Venue":{"role":"symbol","title":"Venue","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Venue"}],"abstract":[{"type":"text","text":"Signifies a real-world location and the data associated to it. Example: A Ski Resort."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/Venue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Venue"}],"url":"\/documentation\/mappy\/venue"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapView","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/SceneView"]},{"title":"Variables","identifiers":["doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MappyVersionNumber","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MappyVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1io.freshworks.Mappy~1documentation~1Mappy~1MapView\/title","value":"MapView"},{"op":"replace","path":"\/references\/doc:~1~1io.freshworks.Mappy~1documentation~1Mappy~1MapView\/fragments","value":[{"kind":"identifier","text":"MapView"}]},{"op":"replace","path":"\/references\/doc:~1~1io.freshworks.Mappy~1documentation~1Mappy~1SceneView\/title","value":"SceneView"},{"op":"replace","path":"\/references\/doc:~1~1io.freshworks.Mappy~1documentation~1Mappy~1SceneView\/fragments","value":[{"kind":"identifier","text":"SceneView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}