{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/AGSGeoViewTouchDelegate-Implementations"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/geoView(_:didTapAtScreenPoint:mapPoint:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/mappy\/mapview\/agsgeoviewtouchdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mappy\/mapview\/agsgeoviewtouchdelegate-implementations"]}],"metadata":{"title":"AGSGeoViewTouchDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"Mappy"}]},"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView"]]},"references":{"doc://io.bemappy.Mappy/documentation/Mappy/MapView/geoView(_:didTapAtScreenPoint:mapPoint:)":{"kind":"symbol","type":"topic","url":"\/documentation\/mappy\/mapview\/geoview(_:didtapatscreenpoint:mappoint:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"geoView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AGSGeoView","preciseIdentifier":"c:objc(cs)AGSGeoView"},{"text":", ","kind":"text"},{"text":"didTapAtScreenPoint","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"mapPoint"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AGSPoint","text":"AGSPoint"},{"kind":"text","text":")"}],"title":"geoView(_:didTapAtScreenPoint:mapPoint:)","role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/geoView(_:didTapAtScreenPoint:mapPoint:)","navigatorTitle":[{"text":"geoView:didTapAtScreenPoint:mapPoint:","kind":"identifier"}]},"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView":{"abstract":[{"type":"text","text":"MapView is an UI class that helps in rendering the 2D map. Once the map is loaded, add the map to MapView and then you can add the same to your UI hierarchy."}],"title":"MapView","type":"topic","kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView","url":"\/documentation\/mappy\/mapview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapView","kind":"identifier"}],"navigatorTitle":[{"text":"MapView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/geoView(_:didTapAtScreenPoint:mapPoint:)"]}],"path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView~1geoView(_:didTapAtScreenPoint:mapPoint:)\/title","value":"geoView:didTapAtScreenPoint:mapPoint:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView~1geoView(_:didTapAtScreenPoint:mapPoint:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"geoView:didTapAtScreenPoint:mapPoint:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/title","value":"MapView"},{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/fragments","value":[{"text":"MapView","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MapView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}