{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"geoView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"geoView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AGSGeoView","preciseIdentifier":"c:objc(cs)AGSGeoView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapAtScreenPoint"},{"kind":"text","text":" "},{"kind":"internalParam","text":"screenPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mapPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AGSPoint","preciseIdentifier":"c:objc(cs)AGSPoint"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mappy\/mapview\/geoview(_:didtapatscreenpoint:mappoint:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mappy\/mapview\/geoview(_:didtapatscreenpoint:mappoint:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapView\/geoView(_:didTapAtScreenPoint:mapPoint:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AGSGeoViewTouchDelegate.geoView(_:didTapAtScreenPoint:mapPoint:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"geoView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AGSGeoView","preciseIdentifier":"c:objc(cs)AGSGeoView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapAtScreenPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mapPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AGSPoint","preciseIdentifier":"c:objc(cs)AGSPoint"},{"kind":"text","text":")"}],"title":"geoView(_:didTapAtScreenPoint:mapPoint:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@Mappy@objc(cs)MapView(im)geoView:didTapAtScreenPoint:mapPoint:","modules":[{"name":"Mappy"}],"navigatorTitle":[{"kind":"identifier","text":"geoView:didTapAtScreenPoint:mapPoint:"}]},"hierarchy":{"paths":[["doc:\/\/io.freshworks.Mappy\/documentation\/Mappy","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapView","doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapView\/AGSGeoViewTouchDelegate-Implementations"]]},"references":{"doc://io.freshworks.Mappy/documentation/Mappy":{"role":"collection","title":"Mappy","abstract":[{"type":"text","text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy","kind":"symbol","type":"topic","url":"\/documentation\/mappy"},"doc://io.freshworks.Mappy/documentation/Mappy/MapView/geoView(_:didTapAtScreenPoint:mapPoint:)":{"role":"symbol","title":"geoView(_:didTapAtScreenPoint:mapPoint:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"geoView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AGSGeoView","preciseIdentifier":"c:objc(cs)AGSGeoView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapAtScreenPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mapPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AGSPoint","preciseIdentifier":"c:objc(cs)AGSPoint"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapView\/geoView(_:didTapAtScreenPoint:mapPoint:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"geoView:didTapAtScreenPoint:mapPoint:"}],"url":"\/documentation\/mappy\/mapview\/geoview(_:didtapatscreenpoint:mappoint:)"},"doc://io.freshworks.Mappy/documentation/Mappy/MapView":{"role":"symbol","title":"MapView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapView"}],"abstract":[{"type":"text","text":"MapView is an UI class that helps in rendering the 2D map. Once the map is loaded, add the map to MapView and then you can add the same to your UI hierarchy."}],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapView"}],"url":"\/documentation\/mappy\/mapview"},"doc://io.freshworks.Mappy/documentation/Mappy/MapView/AGSGeoViewTouchDelegate-Implementations":{"role":"collectionGroup","title":"AGSGeoViewTouchDelegate Implementations","abstract":[],"identifier":"doc:\/\/io.freshworks.Mappy\/documentation\/Mappy\/MapView\/AGSGeoViewTouchDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/mappy\/mapview\/agsgeoviewtouchdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"geoView:didTapAtScreenPoint:mapPoint:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"geoView:didTapAtScreenPoint:mapPoint:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"geoView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AGSGeoView","preciseIdentifier":"c:objc(cs)AGSGeoView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"geoView"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapAtScreenPoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"screenPoint"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapPoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AGSPoint","preciseIdentifier":"c:objc(cs)AGSPoint"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mapPoint"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.freshworks.Mappy~1documentation~1Mappy~1MapView~1geoView(_:didTapAtScreenPoint:mapPoint:)\/title","value":"geoView:didTapAtScreenPoint:mapPoint:"},{"op":"replace","path":"\/references\/doc:~1~1io.freshworks.Mappy~1documentation~1Mappy~1MapView~1geoView(_:didTapAtScreenPoint:mapPoint:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"geoView:didTapAtScreenPoint:mapPoint:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.freshworks.Mappy~1documentation~1Mappy~1MapView\/title","value":"MapView"},{"op":"replace","path":"\/references\/doc:~1~1io.freshworks.Mappy~1documentation~1Mappy~1MapView\/fragments","value":[{"kind":"identifier","text":"MapView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}