{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mappy\/mapview\/initwithcoder:"]}],"identifier":{"url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/initWithCoder:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView"]]},"metadata":{"externalID":"c:@M@Mappy@objc(cs)MapView(im)initWithCoder:","title":"initWithCoder:","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"modules":[{"name":"Mappy"}],"role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"text":"(","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"coder"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://io.bemappy.Mappy/documentation/Mappy/MapView":{"abstract":[{"type":"text","text":"MapView is an UI class that helps in rendering the 2D map. Once the map is loaded, add the map to MapView and then you can add the same to your UI hierarchy."}],"title":"MapView","type":"topic","kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView","url":"\/documentation\/mappy\/mapview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapView","kind":"identifier"}],"navigatorTitle":[{"text":"MapView","kind":"identifier"}]},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/initWithCoder:":{"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/initWithCoder:","title":"initWithCoder:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mappy\/mapview\/initwithcoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/title","value":"MapView","op":"replace"},{"value":[{"text":"MapView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/navigatorTitle","value":[{"text":"MapView","kind":"identifier"}]}]}]}