{"sections":[],"identifier":{"url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/removeUserTrack()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeUserTrack","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView"]]},"metadata":{"externalID":"s:5Mappy7MapViewC15removeUserTrackyyF","modules":[{"name":"Mappy"}],"role":"symbol","title":"removeUserTrack()","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeUserTrack"},{"kind":"text","text":"()"}],"extendedModule":"Mappy","roleHeading":"Instance Method"},"abstract":[{"text":"To completely remove the user track from the map.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mappy\/mapview\/removeusertrack()"]}],"references":{"doc://io.bemappy.Mappy/documentation/Mappy/MapView/removeUserTrack()":{"url":"\/documentation\/mappy\/mapview\/removeusertrack()","title":"removeUserTrack()","abstract":[{"type":"text","text":"To completely remove the user track from the map."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeUserTrack","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/removeUserTrack()","kind":"symbol"},"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView":{"abstract":[{"type":"text","text":"MapView is an UI class that helps in rendering the 2D map. Once the map is loaded, add the map to MapView and then you can add the same to your UI hierarchy."}],"title":"MapView","type":"topic","kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView","url":"\/documentation\/mappy\/mapview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapView","kind":"identifier"}],"navigatorTitle":[{"text":"MapView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/title","value":"MapView"},{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/fragments","op":"replace","value":[{"text":"MapView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/navigatorTitle","value":[{"kind":"identifier","text":"MapView"}],"op":"replace"}]}]}