{"metadata":{"externalID":"s:5Mappy7MapViewC14zoomToLocation8latitude9longitudeySd_SdtF","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"zoomToLocation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"latitude"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"longitude"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"Mappy"}],"role":"symbol","extendedModule":"Mappy","title":"zoomToLocation(latitude:longitude:)","symbolKind":"method"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomToLocation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/mappy\/mapview\/zoomtolocation(latitude:longitude:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView"]]},"identifier":{"url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/zoomToLocation(latitude:longitude:)","interfaceLanguage":"swift"},"references":{"doc://io.bemappy.Mappy/documentation/Mappy/MapView":{"abstract":[{"type":"text","text":"MapView is an UI class that helps in rendering the 2D map. Once the map is loaded, add the map to MapView and then you can add the same to your UI hierarchy."}],"title":"MapView","type":"topic","kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView","url":"\/documentation\/mappy\/mapview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MapView","kind":"identifier"}],"navigatorTitle":[{"text":"MapView","kind":"identifier"}]},"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/zoomToLocation(latitude:longitude:)":{"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/zoomToLocation(latitude:longitude:)","title":"zoomToLocation(latitude:longitude:)","abstract":[],"type":"topic","url":"\/documentation\/mappy\/mapview\/zoomtolocation(latitude:longitude:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zoomToLocation","kind":"identifier"},{"kind":"text","text":"("},{"text":"latitude","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"longitude"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/title","value":"MapView","op":"replace"},{"value":[{"text":"MapView","kind":"identifier"}],"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/navigatorTitle","value":[{"text":"MapView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}