{"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy"]]},"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/event-swift.property","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/interactionOptions","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/isPointingNorth","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/isUserTrackRendered","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/map"]},{"title":"Instance Methods","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/display(route:routeHighlightColor:destinationImage:)","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/displayUserPins(using:)","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/hideUserTrack()","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/removeUserTrack()","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/renderUserTrack(startTime:endTime:userId:)","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/rotateToNorth()","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/select(feature:)","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/setInitialViewpoint()","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/showUserTrack()","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/startNavigation(route:routeHighlightColor:destinationImage:)","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/stopNavigation()","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/zoomToLocation(latitude:longitude:)"]},{"title":"Enumerations","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/Event-swift.enum","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/UserTrackRenderingStatus"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/AGSGeoViewTouchDelegate-Implementations"]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/io.bemappy.Mappy\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/io.bemappy.Mappy\/objc(pl)AGSGeoViewTouchDelegate","doc:\/\/io.bemappy.Mappy\/objc(pl)NSCoding","doc:\/\/io.bemappy.Mappy\/objc(pl)NSObject","doc:\/\/io.bemappy.Mappy\/objc(pl)CALayerDelegate","doc:\/\/io.bemappy.Mappy\/s7CVarArgP","doc:\/\/io.bemappy.Mappy\/s28CustomDebugStringConvertibleP","doc:\/\/io.bemappy.Mappy\/s23CustomStringConvertibleP","doc:\/\/io.bemappy.Mappy\/SQ","doc:\/\/io.bemappy.Mappy\/SH","doc:\/\/io.bemappy.Mappy\/objc(pl)UIAccessibilityIdentification","doc:\/\/io.bemappy.Mappy\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/io.bemappy.Mappy\/objc(pl)UIAppearance","doc:\/\/io.bemappy.Mappy\/objc(pl)UIAppearanceContainer","doc:\/\/io.bemappy.Mappy\/objc(pl)UICoordinateSpace","doc:\/\/io.bemappy.Mappy\/objc(pl)UIDynamicItem","doc:\/\/io.bemappy.Mappy\/objc(pl)UIFocusEnvironment","doc:\/\/io.bemappy.Mappy\/objc(pl)UIFocusItem","doc:\/\/io.bemappy.Mappy\/objc(pl)UIFocusItemContainer","doc:\/\/io.bemappy.Mappy\/objc(pl)UILargeContentViewerItem","doc:\/\/io.bemappy.Mappy\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/io.bemappy.Mappy\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/io.bemappy.Mappy\/objc(pl)UIResponderStandardEditActions","doc:\/\/io.bemappy.Mappy\/5UIKit23UITraitChangeObservableP","doc:\/\/io.bemappy.Mappy\/objc(pl)UITraitEnvironment","doc:\/\/io.bemappy.Mappy\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView"},"metadata":{"role":"symbol","title":"MapView","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"MapView"}],"modules":[{"name":"Mappy"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapView"}],"externalID":"c:@M@Mappy@objc(cs)MapView","symbolKind":"class"},"abstract":[{"type":"text","text":"MapView is an UI class that helps in rendering the 2D map. Once the map is loaded, add the map to MapView and then you can add the same to your UI hierarchy."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapView"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mappy\/mapview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mappy\/mapview"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://io.bemappy.Mappy/documentation/Mappy/MapView/rotateToNorth()":{"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/rotateToNorth()","abstract":[{"type":"text","text":"Rotates the map to the default orientation"}],"kind":"symbol","url":"\/documentation\/mappy\/mapview\/rotatetonorth()","role":"symbol","title":"rotateToNorth()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rotateToNorth"},{"kind":"text","text":"()"}]},"doc://io.bemappy.Mappy/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/isPointingNorth":{"role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/isPointingNorth","type":"topic","abstract":[{"type":"text","text":"Whether the map is pointing north"}],"url":"\/documentation\/mappy\/mapview\/ispointingnorth","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPointingNorth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isPointingNorth","kind":"symbol"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/initWithFrame:":{"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/initWithFrame:","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"initWithFrame:","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"url":"\/documentation\/mappy\/mapview\/initwithframe:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}]},"doc://io.bemappy.Mappy/documentation/Mappy":{"title":"Mappy","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","type":"topic","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"role":"collection","url":"\/documentation\/mappy","kind":"symbol"},"doc://io.bemappy.Mappy/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/select(feature:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/mappy\/mapview\/select(feature:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"select","kind":"identifier"},{"text":"(","kind":"text"},{"text":"feature","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Feature","preciseIdentifier":"s:5Mappy7FeatureV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"text":"A function that highlights and zooms to the feature provided","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the provided feature is nil then it removes any existing selection on the map"}],"title":"select(feature:)","type":"topic","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/select(feature:)"},"doc://io.bemappy.Mappy/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://io.bemappy.Mappy/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://io.bemappy.Mappy/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://io.bemappy.Mappy/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/setInitialViewpoint()":{"role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/setInitialViewpoint()","type":"topic","abstract":[{"type":"text","text":"Restores the map to its initial state where the venue is entirely visible"}],"url":"\/documentation\/mappy\/mapview\/setinitialviewpoint()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setInitialViewpoint","kind":"identifier"},{"text":"()","kind":"text"}],"title":"setInitialViewpoint()","kind":"symbol"},"doc://io.bemappy.Mappy/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/s7CVarArgP","title":"Swift.CVarArg"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/removeUserTrack()":{"role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/removeUserTrack()","type":"topic","abstract":[{"type":"text","text":"To completely remove the user track from the map."}],"url":"\/documentation\/mappy\/mapview\/removeusertrack()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeUserTrack"},{"kind":"text","text":"()"}],"title":"removeUserTrack()","kind":"symbol"},"doc://io.bemappy.Mappy/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/UserTrackRenderingStatus":{"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/mappy\/mapview\/usertrackrenderingstatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserTrackRenderingStatus"}],"type":"topic","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/UserTrackRenderingStatus","title":"MapView.UserTrackRenderingStatus","navigatorTitle":[{"kind":"identifier","text":"UserTrackRenderingStatus"}]},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/isUserTrackRendered":{"title":"isUserTrackRendered","type":"topic","url":"\/documentation\/mappy\/mapview\/isusertrackrendered","abstract":[{"type":"text","text":"Returns ‘true’ if the tracks were rendered regardless of their visibility(Visible\/Hidden)."}],"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/isUserTrackRendered","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isUserTrackRendered","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://io.bemappy.Mappy/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://io.bemappy.Mappy/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/interactionOptions":{"role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/interactionOptions","type":"topic","abstract":[{"type":"text","text":"Options to configure user interactions with the view."}],"url":"\/documentation\/mappy\/mapview\/interactionoptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"interactionOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5Mappy25MapViewInteractionOptionsV","kind":"typeIdentifier","text":"MapViewInteractionOptions"}],"title":"interactionOptions","kind":"symbol"},"doc://io.bemappy.Mappy/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/s23CustomStringConvertibleP"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/showUserTrack()":{"role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/showUserTrack()","type":"topic","abstract":[{"type":"text","text":"To toggle the track’s visibility"}],"url":"\/documentation\/mappy\/mapview\/showusertrack()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showUserTrack"},{"kind":"text","text":"()"}],"title":"showUserTrack()","kind":"symbol"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/initWithCoder:":{"role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/initWithCoder:","type":"topic","abstract":[],"url":"\/documentation\/mappy\/mapview\/initwithcoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","kind":"symbol"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/Event-swift.enum":{"abstract":[],"title":"MapView.Event","type":"topic","url":"\/documentation\/mappy\/mapview\/event-swift.enum","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Event"}],"kind":"symbol","navigatorTitle":[{"text":"Event","kind":"identifier"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/Event-swift.enum"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/renderUserTrack(startTime:endTime:userId:)":{"role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/renderUserTrack(startTime:endTime:userId:)","type":"topic","abstract":[{"type":"text","text":"Renders the user track on the map."}],"url":"\/documentation\/mappy\/mapview\/renderusertrack(starttime:endtime:userid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"renderUserTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"startTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endTime"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier","text":"AnyPublisher"},{"text":"<","kind":"text"},{"text":"UserTrackRenderingStatus","kind":"typeIdentifier","preciseIdentifier":"s:5Mappy7MapViewC24UserTrackRenderingStatusO"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">","kind":"text"}],"title":"renderUserTrack(startTime:endTime:userId:)","kind":"symbol"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/stopNavigation()":{"role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/stopNavigation()","type":"topic","abstract":[{"text":"A function that ends the turn by turn navigation mode","type":"text"}],"url":"\/documentation\/mappy\/mapview\/stopnavigation()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopNavigation","kind":"identifier"},{"text":"()","kind":"text"}],"title":"stopNavigation()","kind":"symbol"},"doc://io.bemappy.Mappy/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)NSCoding"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/AGSGeoViewTouchDelegate-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/AGSGeoViewTouchDelegate-Implementations","type":"topic","abstract":[],"url":"\/documentation\/mappy\/mapview\/agsgeoviewtouchdelegate-implementations","title":"AGSGeoViewTouchDelegate Implementations","kind":"article"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/startNavigation(route:routeHighlightColor:destinationImage:)":{"role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/startNavigation(route:routeHighlightColor:destinationImage:)","type":"topic","abstract":[{"text":"A function that starts the turn by turn navigation mode","type":"text"}],"url":"\/documentation\/mappy\/mapview\/startnavigation(route:routehighlightcolor:destinationimage:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startNavigation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"route"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5Mappy13RouteResponseV","text":"RouteResponse"},{"kind":"text","text":", "},{"text":"routeHighlightColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"destinationImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"RouteTracker","preciseIdentifier":"s:5Mappy12RouteTrackerC"},{"kind":"text","text":"?"}],"title":"startNavigation(route:routeHighlightColor:destinationImage:)","kind":"symbol"},"doc://io.bemappy.Mappy/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)NSObject"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/event-swift.property":{"role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/event-swift.property","type":"topic","abstract":[{"type":"text","text":"A publisher that fires MapView related event"}],"url":"\/documentation\/mappy\/mapview\/event-swift.property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"event","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine18PassthroughSubjectC","text":"PassthroughSubject"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Mappy@objc(cs)MapView","text":"MapView"},{"kind":"text","text":"."},{"text":"Event","preciseIdentifier":"s:5Mappy7MapViewC5EventO","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO","text":"Never"},{"text":">","kind":"text"}],"title":"event","kind":"symbol"},"doc://io.bemappy.Mappy/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://io.bemappy.Mappy/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/map":{"abstract":[{"type":"text","text":"The map that needs to be rendered"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/map","kind":"symbol","title":"map","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"map","kind":"identifier"},{"kind":"text","text":": "},{"text":"Map","kind":"typeIdentifier","preciseIdentifier":"s:5Mappy3MapC"},{"text":"?","kind":"text"}],"url":"\/documentation\/mappy\/mapview\/map"},"doc://io.bemappy.Mappy/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/io.bemappy.Mappy\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://io.bemappy.Mappy/objc(cs)UIView":{"identifier":"doc:\/\/io.bemappy.Mappy\/objc(cs)UIView","title":"UIView","type":"unresolvable"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/hideUserTrack()":{"url":"\/documentation\/mappy\/mapview\/hideusertrack()","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/hideUserTrack()","title":"hideUserTrack()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hideUserTrack","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"To toggle the track’s visibility","type":"text"}]},"doc://io.bemappy.Mappy/SH":{"identifier":"doc:\/\/io.bemappy.Mappy\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://io.bemappy.Mappy/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://io.bemappy.Mappy/objc(pl)UIAppearance":{"identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://io.bemappy.Mappy/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIFocusEnvironment"},"doc://io.bemappy.Mappy/objc(pl)AGSGeoViewTouchDelegate":{"title":"AGSGeoViewTouchDelegate","type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)AGSGeoViewTouchDelegate"},"doc://io.bemappy.Mappy/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIUserActivityRestoring"},"doc://io.bemappy.Mappy/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)CALayerDelegate"},"doc://io.bemappy.Mappy/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIResponderStandardEditActions"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/displayUserPins(using:)":{"role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/displayUserPins(using:)","type":"topic","abstract":[{"type":"text","text":"A function that plots the pins on the map."}],"url":"\/documentation\/mappy\/mapview\/displayuserpins(using:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"displayUserPins","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5Mappy15UserPinLocationV","text":"UserPinLocation"},{"kind":"text","text":"])"}],"title":"displayUserPins(using:)","kind":"symbol"},"doc://io.bemappy.Mappy/SQ":{"type":"unresolvable","identifier":"doc:\/\/io.bemappy.Mappy\/SQ","title":"Swift.Equatable"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView":{"title":"MapView","type":"topic","url":"\/documentation\/mappy\/mapview","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView","abstract":[{"type":"text","text":"MapView is an UI class that helps in rendering the 2D map. Once the map is loaded, add the map to MapView and then you can add the same to your UI hierarchy."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MapView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MapView"}]},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/display(route:routeHighlightColor:destinationImage:)":{"role":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/display(route:routeHighlightColor:destinationImage:)","type":"topic","abstract":[{"type":"text","text":"A function that displays the route on the map."}],"url":"\/documentation\/mappy\/mapview\/display(route:routehighlightcolor:destinationimage:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"display"},{"kind":"text","text":"("},{"text":"route","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RouteResponse","kind":"typeIdentifier","preciseIdentifier":"s:5Mappy13RouteResponseV"},{"kind":"text","text":"?, "},{"text":"routeHighlightColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"destinationImage"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":")","kind":"text"}],"title":"display(route:routeHighlightColor:destinationImage:)","kind":"symbol"},"doc://io.bemappy.Mappy/documentation/Mappy/MapView/zoomToLocation(latitude:longitude:)":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/zoomToLocation(latitude:longitude:)","url":"\/documentation\/mappy\/mapview\/zoomtolocation(latitude:longitude:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomToLocation"},{"kind":"text","text":"("},{"text":"latitude","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"longitude","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"type":"topic","title":"zoomToLocation(latitude:longitude:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"MapView","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MapView"}],"op":"replace"},{"value":[{"text":"MapView","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/initWithCoder:","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/initWithFrame:"]},{"identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/MapView\/AGSGeoViewTouchDelegate-Implementations"],"generated":true,"title":"Default Implementations"}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/io.bemappy.Mappy\/objc(cs)UIView"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/io.bemappy.Mappy\/objc(pl)AGSGeoViewTouchDelegate"],"title":"Conforms To","type":"conformsTo"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapView"},{"text":" : ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/title","value":"MapView","op":"replace"},{"value":[{"text":"MapView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1MapView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}