{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mappy\/sceneview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mappy\/sceneview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/io.bemappy.Mappy\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/io.bemappy.Mappy\/objc(pl)AGSGeoViewTouchDelegate","doc:\/\/io.bemappy.Mappy\/objc(pl)NSCoding","doc:\/\/io.bemappy.Mappy\/objc(pl)NSObject","doc:\/\/io.bemappy.Mappy\/objc(pl)CALayerDelegate","doc:\/\/io.bemappy.Mappy\/s7CVarArgP","doc:\/\/io.bemappy.Mappy\/s28CustomDebugStringConvertibleP","doc:\/\/io.bemappy.Mappy\/s23CustomStringConvertibleP","doc:\/\/io.bemappy.Mappy\/SQ","doc:\/\/io.bemappy.Mappy\/SH","doc:\/\/io.bemappy.Mappy\/s8SendableP","doc:\/\/io.bemappy.Mappy\/objc(pl)UIAccessibilityIdentification","doc:\/\/io.bemappy.Mappy\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/io.bemappy.Mappy\/objc(pl)UIAppearance","doc:\/\/io.bemappy.Mappy\/objc(pl)UIAppearanceContainer","doc:\/\/io.bemappy.Mappy\/objc(pl)UICoordinateSpace","doc:\/\/io.bemappy.Mappy\/objc(pl)UIDynamicItem","doc:\/\/io.bemappy.Mappy\/objc(pl)UIFocusEnvironment","doc:\/\/io.bemappy.Mappy\/objc(pl)UIFocusItem","doc:\/\/io.bemappy.Mappy\/objc(pl)UIFocusItemContainer","doc:\/\/io.bemappy.Mappy\/objc(pl)UILargeContentViewerItem","doc:\/\/io.bemappy.Mappy\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/io.bemappy.Mappy\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/io.bemappy.Mappy\/objc(pl)UIResponderStandardEditActions","doc:\/\/io.bemappy.Mappy\/5UIKit23UITraitChangeObservableP","doc:\/\/io.bemappy.Mappy\/objc(pl)UITraitEnvironment","doc:\/\/io.bemappy.Mappy\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"SceneView is an UI class that helps in rendering the 3D map. Once the scene is loaded, add the scene to SceneView and then you can add the same to your UI hierarchy."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneView"}],"title":"SceneView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Mappy@objc(cs)SceneView","modules":[{"name":"Mappy"}],"navigatorTitle":[{"kind":"identifier","text":"SceneView"}]},"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/event-swift.property","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/interactionOptions","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/isPointingNorth","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/isUserTrackRendered","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/scene"]},{"title":"Instance Methods","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/displayUserPins(using:)","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/hideUserTrack()","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/removeUserTrack()","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/renderUserTrack(startTime:endTime:userId:)","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/rotateToNorth()","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/select(feature:)","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/setInitialViewpoint()","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/showUserTrack()","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/zoomToLocation(latitude:longitude:)"]},{"title":"Enumerations","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/Event-swift.enum","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/UserTrackRenderingStatus"]},{"title":"Default Implementations","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/AGSGeoViewTouchDelegate-Implementations"],"generated":true}],"references":{"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/AGSGeoViewTouchDelegate-Implementations":{"role":"collectionGroup","title":"AGSGeoViewTouchDelegate Implementations","abstract":[],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/AGSGeoViewTouchDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/mappy\/sceneview\/agsgeoviewtouchdelegate-implementations"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/showUserTrack()":{"role":"symbol","title":"showUserTrack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showUserTrack"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"To toggle the track’s visibility"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/showUserTrack()","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/showusertrack()"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/hideUserTrack()":{"role":"symbol","title":"hideUserTrack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideUserTrack"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"To toggle the track’s visibility"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/hideUserTrack()","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/hideusertrack()"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/removeUserTrack()":{"role":"symbol","title":"removeUserTrack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeUserTrack"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"To completely remove the user track from the scene."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/removeUserTrack()","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/removeusertrack()"},"doc://io.bemappy.Mappy/objc(pl)AGSGeoViewTouchDelegate":{"type":"unresolvable","title":"AGSGeoViewTouchDelegate","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)AGSGeoViewTouchDelegate"},"doc://io.bemappy.Mappy/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/io.bemappy.Mappy\/s7CVarArgP"},"doc://io.bemappy.Mappy/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/io.bemappy.Mappy\/s8SendableP"},"doc://io.bemappy.Mappy/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)NSObject"},"doc://io.bemappy.Mappy/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/io.bemappy.Mappy\/s28CustomDebugStringConvertibleP"},"doc://io.bemappy.Mappy/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/mappy\/sceneview\/initwithcoder:"},"doc://io.bemappy.Mappy/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/interactionOptions":{"role":"symbol","title":"interactionOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactionOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SceneViewInteractionOptions","preciseIdentifier":"s:5Mappy27SceneViewInteractionOptionsV"}],"abstract":[{"type":"text","text":"Options to configure user interactions with the view."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/interactionOptions","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/interactionoptions"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/setInitialViewpoint()":{"role":"symbol","title":"setInitialViewpoint()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setInitialViewpoint"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Restores the scene to its initial state where the venue is entirely visible"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/setInitialViewpoint()","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/setinitialviewpoint()"},"doc://io.bemappy.Mappy/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)CALayerDelegate"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/isPointingNorth":{"role":"symbol","title":"isPointingNorth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPointingNorth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the scene is pointing north"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/isPointingNorth","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/ispointingnorth"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/isUserTrackRendered":{"role":"symbol","title":"isUserTrackRendered","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserTrackRendered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns ‘true’ if the tracks were rendered regardless of their visibility(Visible\/Hidden)."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/isUserTrackRendered","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/isusertrackrendered"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/event-swift.property":{"role":"symbol","title":"event","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SceneView","preciseIdentifier":"c:@M@Mappy@objc(cs)SceneView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"s:5Mappy9SceneViewC5EventO"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"A publisher that fires MapView related event"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/event-swift.property","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/event-swift.property"},"doc://io.bemappy.Mappy/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UITraitEnvironment"},"doc://io.bemappy.Mappy/documentation/Mappy":{"role":"collection","title":"Mappy","abstract":[{"type":"text","text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","kind":"symbol","type":"topic","url":"\/documentation\/mappy"},"doc://io.bemappy.Mappy/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIDynamicItem"},"doc://io.bemappy.Mappy/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/io.bemappy.Mappy\/SQ"},"doc://io.bemappy.Mappy/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIUserActivityRestoring"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/select(feature:)":{"role":"symbol","title":"select(feature:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"select"},{"kind":"text","text":"("},{"kind":"externalParam","text":"feature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Feature","preciseIdentifier":"s:5Mappy7FeatureV"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"A function that highlights and zooms to the feature provided"},{"type":"text","text":" "},{"type":"text","text":"If the provided feature is nil then it removes any existing selection on the scene"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/select(feature:)","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/select(feature:)"},"doc://io.bemappy.Mappy/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UICoordinateSpace"},"doc://io.bemappy.Mappy/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/io.bemappy.Mappy\/s23CustomStringConvertibleP"},"doc://io.bemappy.Mappy/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIAppearanceContainer"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/mappy\/sceneview\/initwithframe:"},"doc://io.bemappy.Mappy/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIAppearance"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/UserTrackRenderingStatus":{"role":"symbol","title":"SceneView.UserTrackRenderingStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserTrackRenderingStatus"}],"abstract":[],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/UserTrackRenderingStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserTrackRenderingStatus"}],"url":"\/documentation\/mappy\/sceneview\/usertrackrenderingstatus"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/displayUserPins(using:)":{"role":"symbol","title":"displayUserPins(using:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayUserPins"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UserPinLocation","preciseIdentifier":"s:5Mappy15UserPinLocationV"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"A function that plots the pins on the scene."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/displayUserPins(using:)","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/displayuserpins(using:)"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/renderUserTrack(startTime:endTime:userId:)":{"role":"symbol","title":"renderUserTrack(startTime:endTime:userId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderUserTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"startTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UserTrackRenderingStatus","preciseIdentifier":"s:5Mappy9SceneViewC24UserTrackRenderingStatusO"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Renders the user track on the scene."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/renderUserTrack(startTime:endTime:userId:)","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/renderusertrack(starttime:endtime:userid:)"},"doc://io.bemappy.Mappy/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)NSCoding"},"doc://io.bemappy.Mappy/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UILargeContentViewerItem"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView":{"role":"symbol","title":"SceneView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneView"}],"abstract":[{"type":"text","text":"SceneView is an UI class that helps in rendering the 3D map. Once the scene is loaded, add the scene to SceneView and then you can add the same to your UI hierarchy."}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SceneView"}],"url":"\/documentation\/mappy\/sceneview"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/scene":{"role":"symbol","title":"scene","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Scene","preciseIdentifier":"s:5Mappy5SceneC"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The scene that needs to be rendered"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/scene","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/scene"},"doc://io.bemappy.Mappy/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIFocusItem"},"doc://io.bemappy.Mappy/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/io.bemappy.Mappy\/5UIKit23UITraitChangeObservableP"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/zoomToLocation(latitude:longitude:)":{"role":"symbol","title":"zoomToLocation(latitude:longitude:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomToLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/zoomToLocation(latitude:longitude:)","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/zoomtolocation(latitude:longitude:)"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/rotateToNorth()":{"role":"symbol","title":"rotateToNorth()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotateToNorth"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Rotates the scene to the default orientation"}],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/rotateToNorth()","kind":"symbol","type":"topic","url":"\/documentation\/mappy\/sceneview\/rotatetonorth()"},"doc://io.bemappy.Mappy/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/io.bemappy.Mappy\/SH"},"doc://io.bemappy.Mappy/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIFocusItemContainer"},"doc://io.bemappy.Mappy/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/io.bemappy.Mappy\/objc(cs)UIView"},"doc://io.bemappy.Mappy/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIAccessibilityIdentification"},"doc://io.bemappy.Mappy/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIResponderStandardEditActions"},"doc://io.bemappy.Mappy/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIFocusEnvironment"},"doc://io.bemappy.Mappy/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)UIPasteConfigurationSupporting"},"doc://io.bemappy.Mappy/documentation/Mappy/SceneView/Event-swift.enum":{"role":"symbol","title":"SceneView.Event","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Event"}],"abstract":[],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/Event-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Event"}],"url":"\/documentation\/mappy\/sceneview\/event-swift.enum"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SceneView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SceneView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SceneView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/initWithCoder:","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/initWithFrame:"]},{"title":"Default Implementations","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/SceneView\/AGSGeoViewTouchDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/io.bemappy.Mappy\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/io.bemappy.Mappy\/objc(pl)AGSGeoViewTouchDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/title","value":"SceneView"},{"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1SceneView\/fragments","value":[{"kind":"identifier","text":"SceneView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}