{"variants":[{"paths":["\/documentation\/mappy\/tracksservice"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mappy\/tracksservice"]}],"metadata":{"modules":[{"name":"Mappy"}],"externalID":"c:@M@Mappy@objc(cs)TracksService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TracksService"}],"navigatorTitle":[{"text":"TracksService","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","title":"TracksService"},"hierarchy":{"paths":[["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy"]]},"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/init()"],"generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/renderUserTracks(on:layerId:userId:venueId:startTime:endTime:)"],"anchor":"Instance-Methods","generated":true},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/AGSAuthenticationManagerDelegate-Implementations"]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/io.bemappy.Mappy\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/io.bemappy.Mappy\/objc(pl)AGSAuthenticationManagerDelegate","doc:\/\/io.bemappy.Mappy\/objc(pl)NSObject","doc:\/\/io.bemappy.Mappy\/s7CVarArgP","doc:\/\/io.bemappy.Mappy\/s8CopyableP","doc:\/\/io.bemappy.Mappy\/s28CustomDebugStringConvertibleP","doc:\/\/io.bemappy.Mappy\/s23CustomStringConvertibleP","doc:\/\/io.bemappy.Mappy\/SQ","doc:\/\/io.bemappy.Mappy\/SH","doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksProvider"],"title":"Conforms To"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TracksService"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://io.bemappy.Mappy/documentation/Mappy/TracksService/init()":{"title":"init()","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/init()","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/mappy\/tracksservice\/init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://io.bemappy.Mappy/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/io.bemappy.Mappy\/SH"},"doc://io.bemappy.Mappy/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/io.bemappy.Mappy\/objc(cs)NSObject"},"doc://io.bemappy.Mappy/objc(pl)AGSAuthenticationManagerDelegate":{"type":"unresolvable","title":"AGSAuthenticationManagerDelegate","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)AGSAuthenticationManagerDelegate"},"doc://io.bemappy.Mappy/documentation/Mappy":{"kind":"symbol","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy","title":"Mappy","url":"\/documentation\/mappy","abstract":[{"text":"Mappy provides an elegant and composable interface for mapping, geocoding, and routing.","type":"text"}],"type":"topic","role":"collection"},"doc://io.bemappy.Mappy/documentation/Mappy/TracksService":{"role":"symbol","title":"TracksService","navigatorTitle":[{"kind":"identifier","text":"TracksService"}],"url":"\/documentation\/mappy\/tracksservice","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TracksService","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService"},"doc://io.bemappy.Mappy/documentation/Mappy/TracksService/AGSAuthenticationManagerDelegate-Implementations":{"role":"collectionGroup","title":"AGSAuthenticationManagerDelegate Implementations","url":"\/documentation\/mappy\/tracksservice\/agsauthenticationmanagerdelegate-implementations","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/AGSAuthenticationManagerDelegate-Implementations"},"doc://io.bemappy.Mappy/documentation/Mappy/TracksService/renderUserTracks(on:layerId:userId:venueId:startTime:endTime:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderUserTracks"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AGSGeoModel","text":"AGSGeoModel"},{"text":", ","kind":"text"},{"text":"layerId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"venueId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"startTime","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"text":"endTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier","text":"AnyPublisher"},{"kind":"text","text":"<"},{"text":"AGSFeatureLayer","preciseIdentifier":"c:objc(cs)AGSFeatureLayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"TracksProviderError","preciseIdentifier":"s:5Mappy19TracksProviderErrorO","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/mappy\/tracksservice\/renderusertracks(on:layerid:userid:venueid:starttime:endtime:)","abstract":[],"kind":"symbol","type":"topic","role":"symbol","title":"renderUserTracks(on:layerId:userId:venueId:startTime:endTime:)","identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/renderUserTracks(on:layerId:userId:venueId:startTime:endTime:)"},"doc://io.bemappy.Mappy/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/io.bemappy.Mappy\/s23CustomStringConvertibleP"},"doc://io.bemappy.Mappy/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/io.bemappy.Mappy\/s7CVarArgP"},"doc://io.bemappy.Mappy/documentation/Mappy/TracksProvider":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TracksProvider","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TracksProvider"}],"abstract":[],"identifier":"doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksProvider","url":"\/documentation\/mappy\/tracksprovider","title":"TracksProvider","role":"symbol","type":"topic"},"doc://io.bemappy.Mappy/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/io.bemappy.Mappy\/s28CustomDebugStringConvertibleP"},"doc://io.bemappy.Mappy/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/io.bemappy.Mappy\/SQ"},"doc://io.bemappy.Mappy/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/io.bemappy.Mappy\/s8CopyableP"},"doc://io.bemappy.Mappy/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/io.bemappy.Mappy\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"TracksService","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"TracksService","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"TracksService"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/init()"]},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/io.bemappy.Mappy\/documentation\/Mappy\/TracksService\/AGSAuthenticationManagerDelegate-Implementations"]}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/io.bemappy.Mappy\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/io.bemappy.Mappy\/objc(pl)AGSAuthenticationManagerDelegate"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"TracksService","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService~1init()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService~1init()\/fragments","op":"replace"},{"value":"TracksService","op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService\/title"},{"path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService\/fragments","op":"replace","value":[{"kind":"identifier","text":"TracksService"}]},{"value":[{"kind":"identifier","text":"TracksService"}],"op":"replace","path":"\/references\/doc:~1~1io.bemappy.Mappy~1documentation~1Mappy~1TracksService\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}